---
- name: Restart 6to4 interface
  ansible.builtin.command:
    argv:
      - /sbin/ifdown
      - --force
      - 6to4
  changed_when: true

- name: Restart 6to4 interface
  ansible.builtin.command:
    argv:
      - /sbin/ifup
      - 6to4
  register: output
  changed_when: output.rc == 0

...
