---
name: ansible-galaxy-publish
on:
  push:
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ansible-lint
        run: sudo apt-get -oInstall-Recommends=false install ansible-lint
      - name: Run ansible-lint
        run: ansible-lint --profile production --strict .
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install ansible-galaxy CLI
        run: sudo apt-get -oInstall-Recommands=false install ansible-core
      - name: Import to Ansible Galaxy
        run: ansible-galaxy role import --token ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }} ${GITHUB_REPOSITORY_OWNER} ${GITHUB_REPOSITORY#*\/}
...
